#!/usr/bin/env python3
"""Generate the repository root README.md from package README files.

This script replaces the auto-generated section between
<!-- BEGIN AUTOGENERATED:START --> and <!-- END AUTOGENERATED:END -->
with the latest contents of the package README files.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
AGENTS = ROOT / "airo-teleop-agents" / "README.md"
DEVICES = ROOT / "airo-teleop-devices" / "README.md"

START = "<!-- BEGIN AUTOGENERATED:START -->"
END = "<!-- END AUTOGENERATED:END -->"

agents_text = AGENTS.read_text(encoding="utf-8") if AGENTS.exists() else ""
devices_text = DEVICES.read_text(encoding="utf-8") if DEVICES.exists() else ""

generated_block = (
    f"{START}\n"
    "\n"
    "---\n"
    "\n"
    "### airo-teleop-devices (from `airo-teleop-devices/README.md`)\n"
    "\n"
    f"{devices_text}\n"
    "\n"
    "---\n"
    "\n"
    "### airo-teleop-agents (from `airo-teleop-agents/README.md`)\n"
    "\n"
    f"{agents_text}\n"
    "\n"
    f"{END}\n"
)

if README.exists():
    text = README.read_text(encoding="utf-8")
    if START in text and END in text:
        pre, rest = text.split(START, 1)
        _, post = rest.split(END, 1)
        new_text = pre + generated_block + post
    else:
        # Overwrite entire README with a generated template
        header = (
            "# airo-teleop\n\n"
            "> This file is **auto-generated** from `airo-teleop-agents/README.md` and `airo-teleop-devices/README.md`.\n"
            "> To update it, edit those files and run `python scripts/generate_readme.py`.\n\n"
        )
        new_text = header + generated_block
else:
    header = (
        "# airo-teleop\n\n"
        "> This file is **auto-generated** from `airo-teleop-agents/README.md` and `airo-teleop-devices/README.md`.\n"
        "> To update it, edit those files and run `python scripts/generate_readme.py`.\n\n"
    )
    new_text = header + generated_block

if new_text != text if README.exists() else True:
    README.write_text(new_text, encoding="utf-8")
    print("README.md updated")
else:
    print("README.md already up to date")
